apiVersion: v1
kind: Service
metadata:
  name: loan-api
  namespace: loan-app
spec:
  selector:
    app: loan-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
