apiVersion: v1
kind: Service
metadata:
  name: loan-ui
  namespace: loan-app
spec:
  selector:
    app: loan-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
